# Generated by Django 4.0.6 on 2022-10-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0005_alter_customuser_first_name_attendancereportstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereportstaff',
            name='attendance_status',
            field=models.TextField(),
        ),
    ]
