# Generated by Django 4.0.6 on 2022-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0007_rename_stafff_id_notificationstaffs_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereportstaff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancereportstaff',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='attendancereportstaff',
            name='intime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendancereportstaff',
            name='outtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancereportstaff',
            name='attendance_date',
            field=models.DateField(null=True),
        ),
    ]
