# Generated by Django 4.0.6 on 2022-10-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0010_attendancereportstaff_intime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereportstaff',
            name='intime',
        ),
        migrations.RemoveField(
            model_name='attendancereportstaff',
            name='outtime',
        ),
    ]
