# Generated by Django 4.0.6 on 2022-10-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0011_remove_attendancereportstaff_intime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereportstaff',
            name='intime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendancereportstaff',
            name='outtime',
            field=models.TimeField(null=True),
        ),
    ]
