# Generated by Django 4.0.6 on 2022-10-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0012_attendancereportstaff_intime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereportstaff',
            name='missing_punch',
            field=models.TimeField(null=True),
        ),
    ]
