# Generated by Django 4.0.6 on 2022-10-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0013_attendancereportstaff_missing_punch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereportstaff',
            name='missing_punch',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
