# Generated by Django 4.0.6 on 2022-10-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0014_alter_attendancereportstaff_missing_punch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereportstaff',
            name='missing_punch',
        ),
    ]
