# Generated by Django 4.0.6 on 2022-11-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0015_remove_attendancereportstaff_missing_punch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='leave_date',
        ),
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='leave_message',
        ),
        migrations.AddField(
            model_name='leavereportstaff',
            name='leave_enddate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavereportstaff',
            name='leave_startdate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
