# Generated by Django 4.0.6 on 2022-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0016_remove_leavereportstaff_leave_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_startdate',
            field=models.DateField(null=True),
        ),
    ]
