# Generated by Django 4.0.6 on 2022-11-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0017_alter_leavereportstaff_leave_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='updated_at',
        ),
    ]
