# Generated by Django 4.0.6 on 2022-11-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0019_remove_attendancereportstaff_attendance_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='staff_id',
        ),
        migrations.DeleteModel(
            name='AttendanceReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
    ]
